# original courtesy of https://shift.click/blog/github-actions-rust/

name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:

  check-and-test:
    name: Test Rust ${{ matrix.rust }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - run: cargo check --workspace --all-targets --verbose
      - run: cargo test --verbose --workspace --all-features